name = "MarkdownAST"
uuid = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com> and contributors"]
version = "0.1.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"
AbstractTrees = "0.4"

[workspace]
projects = ["test", "docs"]
