name = "MarkdownAST"
uuid = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
